emc4j:
  maven:
    directory: ${user.home}/.m2/repository
    redirectionsEnabled: false
    redirect:
      - groupId: com.treilhes.jfxplace
        artifactId: tray.api
        path: ../../../../tray.api/target/classes
      - groupId: com.treilhes.jfxplace
        artifactId: tray.app
        path: ../../../../tray.app/target/classes

server:
  port: 8080

spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true

springdoc:
  show-actuator: true