image: maven:3.9-eclipse-temurin-25

variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

stages:
  - build
  - build-sonar

before_script:
  - mkdir -p /cache/repository
  - echo "$MVN_SETTINGS_NEXUS" > ~/.m2/settings.xml

build-job:
  tags:
    - linux
  image: docker.treilhes.home/jfxapps/builder-linux:latest
  stage: build
  script:
    - mvn -Dmaven.repo.local=/cache/repository -B -ntp clean $MAVEN_GOAL -P headless -T 1C
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      variables:
        MAVEN_GOAL: "deploy"
    - when: always
      variables:
        MAVEN_GOAL: "install"

build-sonar:
  tags:
    - linux
  image: docker.treilhes.home/jfxapps/builder-linux:latest
  stage: build-sonar
      
  script: 
    - mvn -Dmaven.repo.local=/cache/repository -ntp verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -P coverage,headless -T 1C
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'
    - if: $CI_COMMIT_BRANCH == 'develop'