emc4j:
  registry:
    snapshotsAllowed: true
#    defaults:
#      manager:
#        groupId: com.treilhes.jfxplace
#        artifactId: manager.registry
#        mandatory: true

  maven:
    directory: ${user.home}/.m2/repository
    redirectionsEnabled: true
    redirect:
      - groupId: com.treilhes.jfxplace
        artifactId: manager.app
        path: ../../../../manager.app/target/classes

server:
  port: 8080

spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true

springdoc:
  show-actuator: true