<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.treilhes.jfxplace</groupId>
        <artifactId>jfxplace.app.debugtools</artifactId>
        <version>${debugtools.version}</version>
    </parent>
    <artifactId>debugtools.registry</artifactId>

    <build>
        <plugins>
            <plugin>
                <groupId>com.treilhes.emc4j</groupId>
                <artifactId>emc4j-registry-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>generate-registry-resources</id>
                        <phase>generate-resources</phase>
                        <goals>
                            <goal>emc4jRegistry</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <format>json</format>
                    <registry>
                        <uuid>0a6ae529-01fd-49d4-b666-d3af68587b41</uuid>
                        <applications>
                            <application>
                                <uuid>d81e5dd6-7dc2-4ae3-8bb8-448996e359b8</uuid>
                                <splash>jfxplace_debugtools_256x256.jpeg</splash>
                                <dependency>
                                    <groupId>com.treilhes.jfxplace</groupId>
                                    <artifactId>debugtools.api</artifactId>
                                    <version>${debugtools.version}</version>
                                </dependency>
                                <description>
                                    <image>jfxplace_debugtools_256x256.jpeg</image>
                                    <title>jfxplace debugtools</title>
                                    <text>Helper application for jfxplace application development</text>
                                </description>
                                <extensions>
                                    <extension>
                                        <uuid>d92345ef-c549-4a60-baff-ee8c39cac11a</uuid>
                                        <dependency>
                                            <groupId>com.treilhes.jfxplace</groupId>
                                            <artifactId>debugtools.app</artifactId>
                                            <version>${debugtools.version}</version>
                                        </dependency>
                                    </extension>
                                    <extension>
                                        <uuid>5aadfc19-93f1-4d0b-b21a-c5d7ad5a2b05</uuid>
                                        <dependency>
                                            <groupId>com.treilhes.jfxplace</groupId>
                                            <artifactId>debugtools.db</artifactId>
                                            <version>${debugtools.version}</version>
                                        </dependency>
                                    </extension>
                                </extensions>
                            </application>
                        </applications>
                    </registry>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>