emc4j:
  registry:
    snapshotsAllowed: true
    defaults:
      sample:
        groupId: com.treilhes.jfxplace
        artifactId: sample.registry
        mandatory: true

  maven:
    directory: ${user.home}/.m2/repository
    redirectionsEnabled: true
    redirect:
      - groupId: com.treilhes.jfxplace
        artifactId: sample.app
        path: ../../../../sample.app/target/classes

server:
  port: 8080

spring:
  h2:
    console:
      enabled: false
  jpa:
    show-sql: true

springdoc:
  show-actuator: true